INSERT INTO tb_raca (nome_raca, ativo) VALUES
('Afganhound', true),
('srd', true),
('Agapornis', true),
('Airedale Terrier', true),
('Albanês', true),
('American Staffordshire Terrier', true),
('Australian Cattle Dog', true),
('Basenji', true),
('Basset Hound', true),
('Beagle', true),
('Bengal', true),
('Bichon Frisé', true),
('Boiadeiro de Berna', true),
('Border Collie', true),
('Borki', true),
('Boston Terrier', true),
('Boxer', true),
('Bretão Espanhol', true),
('Bull Dog Frances', true),
('Bull Terrier', true),
('Bulldog Campeiro', true),
('BulldogInglês', true),
('Cane Corso', true),
('Chihuahua', true),
('Chow-Chow', true),
('Cocker Americano', true),
('Cocker Spaniel', true),
('Collie', true),
('Dachshund', true),
('Dálmata', true),
('Doberman Pinscher', true),
('Dogo Argentino', true),
('Dogue Alemão', true),
('Exótico', true),
('Fila Brasileiro', true),
('Fox Paulistinha', true),
('Fox Terrier', true),
('Galgo', true),
('Golden Retriever', true),
('Greyhound italiano', true),
('Himalaio', true),
('Husky Siberiano', true),
('Labrador', true),
('Lhasa Apso', true),
('Lulu da Pomerânia', true),
('Maine Coon', true),
('Maltês', true),
('Mastif Ingles', true),
('Mastin Napolitano', true),
('Old English Sheepdog', true),
('Oriental', true),
('Papillon', true),
('Pastor Alemão', true),
('Pastor Australiano', true),
('Pastor Belga', true),
('Pastor Canadense', true),
('Pastor Shetland', true),
('Pequinês', true),
('Persa', true),
('Pinscher', true),
('Pit Bull', true),
('Pointer', true),
('Pointer Inglês', true),
('Poodle', true),
('Pug', true),
('Rottweiler', true),
('Sagrado da Birmânia', true),
('Samoieda', true),
('Sanhaçu', true),
('São Bernardo', true),
('Schnauzer', true),
('Scottish Terrier', true),
('Setter Inglês', true),
('Setter Irlandês', true),
('Sharpei', true),
('Shiba Inu', true),
('Shih Tzu', true),
('Siamês', true),
('SRD', true),
('Terrier Brasileiro', true),
('Tibetan Terrier', true),
('Weimaraner', true),
('West Highland White Terrier', true),
('Yorkshire Terrier', true);
